### ISSUE TITLE
the problem of print scu

### ISSUE THREAD

**Issue by oupable** [fo-dicom/fo-dicom-samples#1]
there are many problems when tested the print scu with other print scp application.for example, there is no A-AssicationRQ,can't set SOPInstanceUID to N-Action Request which from response of the second N-Create. Please fix it.Thanks.

**Comment by anders9ustafsson** [comment]
@oupable The issues are fixed in the *fo-dicom development* branch, but we have not yet published updated NuGet packages. When new NuGet packages are released and the references in *fo-dicom-samples* are updated, issues will be resolved here as well.

If you are in a hurry, you can download and build the *fo-dicom* source, and then reference your locally built assemblies instead.
