### ISSUE TITLE
printscp_resize

### ISSUE THREAD

**Issue by ddbxyrj** [fo-dicom/fo-dicom-samples#22]
for CT and MR, I think every dcm should be 521*521 pix. And I found a lot of company just send a picture which contains 8*8 frames(stand 1/1), maybe for convenient purpose, and this process will need the CT to resizing the pictures. 
I wonder if we can associate with CT that we need row and array print, that would send me 64 dcm pictures for 8*8?
If CT send me one picture, And I want to associate with to send me not resizing picture,Is this possible? For example, 8*8 will send me 8*512*8*8*512 pixs(just for example), and 1*1 send me 1*512*1*512.
I found some printscu just calling a radom ae_title,so which is elegant way to receive calling ae title and just take this ae_title as print_scp's ae_title in the rest association?
Last, thank you great work， and you apply!

**Comment by gofal** [comment]
Sorry, but I did not get what you actual question is.
First of all, it is true that is very common that CT have 512x512 pixels, but you can/should never rely on that. new ct have 1024x1024, reconstructions are non square. And for MR there is no such common resolution, they are often smaller than 512 pixels. 
You mention that some vendors send one image with several frames instead of several files with one frame each. you should take a look at the SOP Class UID of these images. while the CT-SOP Class describes the "old" 1-frame images, the new EnhancedCT allows multiframe. this has some advantages because the stack of images is in one place instead in several files which have to be collected. And you do not have to store the same renundand data like Patient- and Study-data in all of the files but only once. I am sure in future you will find more and more vendors sending EnhancedCT and EnhancedMR. 
But this should not be relevant in Print SCP. Because as a print scp you do not receive the image datasets, but you receive a FilmSession with FilmBoxes which contain the pixels to be printed. So I do not see what the question here is.

What do you mean with the "send me 64 dcm pictures for 88"? And what exactly do you mean with the resizing of the pictures?

Because of the title I assume you are implementing the Print SCP. Within the association request method you have the possibility to do some verification or configuration by evaluating the called AET or calling AET. For example some print scp do have several windows printers configured. And depending on which called AET the client sends the print scp forwards the print job to a different windows printer. Or depending on the calling AET the print scp takes some different configuration like the header text (print the logo of the hospital or an other logo of the department,..). So it is completely up to you to deal with the AETs. If you do not care abot the AETs, then just ignore them.

**Comment by ddbxyrj** [comment]
Tank you reply:)
There just one goal for me . Recognize the receiving picture when using print SCP and then find out the picture linked to which patient id or access number. One way is to ORC the picture areas. Another way is to find the original dicom that used to generate the picture ,then read out the dicom tags.
If using ORC method ,it is more efficient that print scp receiving eight row multiply by eight column pictures, which would be Sixty-four pictures .However many print scu will just sent one picture. In one  picture ,there are Sixty-four cells. It is necessary to cut every picture out.In this case, if print scu send one picture but don’t resizing ,that would be also great .Suppose row eight column eight has 800 multiply by 800 pixels ,five row multiply by five column would be 500 multiply by 500 pixels. But we always receiving 500 multiply by 500 pixels despite the typesetting (eight row multiply by eight column,three row multiply by three column ).So I wonder if print scp can send some association in p-data to tell print scu send picture in the format I want(either multipule pictures or don't resizing). I found dicom support image N-set and annotation.
If using another way to which is to find tag .It would be best practice. Is it possible we can find the relations that link the date which dicom scp receiving and access number or patient id or tag like that(maybe should find the original dicom file).

**Comment by gofal** [comment]
Ah, now I understand. But I have to disappoint you: there is no way as print SCP to tell the print SCU wich format to use.
There is only one possibility: You could define in your dicom conformance statement that you only support Standard1x1 format. And if a print scu sends any other format you reject the association. But this is not very good for users and I am affraid you will hardly find someone who wants to use your application.
It is a very widly common problem that the print scp wants to link the print job to a patient. But that is simply not possible. A client may without problems print the images of different patients in one job (of course the images have to be annotated). Or the print scu prints some quality testing images without any patient context.
Doing it with OCR may be the only way - but it is a very risky way, you really have to deal with a lot of possible situations....

**Comment by ddbxyrj** [comment]
OCR is very risky. I totally agree that.  Philips CT printing picture have an title on its top left. And some GE ct will send you depended picture. We develop an system to do the OCR job. The system will not mistake any number. But it will take our a lot of time to prepare the structure information for every machine.
Thank you information.
