### ISSUE TITLE
Problem in PrintScu in Agfa Printer

### ISSUE THREAD

**Issue by mhmmd7777** [fo-dicom/fo-dicom-samples#28]
Hi
I have agfa drystar 5503 printer and i want to use your print scu sample, but i have this error: "Film session SOP instance hierarchy does not contain image box SOP instances (empty page)"
I think because my printer won't support N-Events, there is a way to send request without N-Events?! 
Sorry for my bad language :(

**Comment by gofal** [comment]
The Print SCU only uses NCreate, NSet and NAction (NDelete should also be called at the end, but is missing in the sample).
The message you get from DryStar is a Warning B603, that you want to print a film session where no image box is accociated. This association happens within the `filmBoxRequest.OnResponseReceived`-Handler.

This issue seems for me to be releated to https://github.com/fo-dicom/fo-dicom/issues/652. In the sample first all the Requests are created and added to the DicomClient instance and sent at once in one association. It may happen, that there are some requests sent and the OnResponseReceived-Handler is called asynchronously with some latency. This would explain, why the instanceuids are not set correctly on the fomBoxRequest.OnResponseReceived-Handler which results in "empty pages".

I would recomment, call the `dicomClient.Send(...)` more often. The dicom print protocol allows to send the various NSet and NCreate requests in different associations. Maybe you call the .Send() method after every single `dicomClient.AddRequest(..)`?

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
