### ISSUE TITLE
Circumventing C-GET

### ISSUE THREAD

**Issue by cass436** [fo-dicom/fo-dicom-samples#52]
Hi everyone,

I am new to DICOM, so please excuse if this question is trivial or redundant. Generally, I want to develop an application that pulls studies with a specific accession number from PACS and stores the image files on the local disk. I have found a way to search for the study and then build a C-GET request, however, only few vendors have implemented C-GET, so it seems I will have to use C-MOVE.

What would be the best approach here? Is it feasible to create a SCP in code during runtime (after registering it with the server) and then transfer the data to it? How would I then access the files that have been moved?

Thanks for any help on this issue!

Best,

Peter

**Comment by gofal** [comment]
Not an easy question. Because there are several possibilities and each one haveing some advantages and disadvantages.

Agree, it is very sad that so few vendors support C-Get. So implementing C-Move might be neccessary.

Of course it is feasible to create a SCP server instance only during runtime within the same process. Of course the connection parameters have to be predefined, because the C-Move-SCP has to know where to open the new connection to.
Creating a StoreSCP in code is as easy as calling `var server = DicomServer.Create<CStoreSCP>(port);'.

advantage of this strategy:
- saves memory because the Store SCP only lives as long as it is really needed. So if retrieving data via c-move is only done semdom you do not need to consume the tcp port while never receiving data.
- sending notifications of images received to the C-Move-SCU can be done very simply by calling delegates, invoking events, enqueueing in static collections, .... because everything happens within the same process

disadvantage of this strategy:
- you have to be careful about multithreading. there can be only one instance of Store SCP per port permachine. So if there are two requests simultanously there still only may be 1 instance of the server. 
- some failures that may happen in your storescp or c-move-SCU also tear down the other application. 
- if you need to run on 32bit windows (today still this requirement exists) then the total memory of both parts is limited by 2GB. if you have two separate processes then you have more memory available.

This are the first ideas that came into my mind.

**Comment by gofal** [comment]
I will close this due to inactivity. Please feel free to reopen this issue if the issue still exists.
