### ISSUE TITLE
Properly structuring CMOVE request

### ISSUE THREAD

**Issue by pcopley** [fo-dicom/fo-dicom-samples#55]
When using the CMOVE example as written at the bottom of https://github.com/fo-dicom/fo-dicom I get the error "Refused: SOP class not supported." I can execute the CMOVE directly via DCMTK fine so I am just not setting something up correctly with FO but I can't figure out what the issue is.

Working DCMTK command:

```
PS> movescu -v -S -k QueryRetrieveLevel=STUDY -k StudyInstanceUID=[REMOVED] -aet TEST1 -aec TEST2 -aem TEST3 [IP_REMOVED] 104
I: Requesting Association
I: Association Accepted (Max Send PDV: 65524)
I: Sending Move Request (MsgID 1)
I: Request Identifiers:
I:
I: # Dicom-Data-Set
I: # Used TransferSyntax: Little Endian Explicit
I: (0008,0052) CS [STUDY] # 6, 1 QueryRetrieveLevel
I: (0020,000d) UI [StudyInstanceUID_REMOVED] # 46, 1 StudyInstanceUID
I:
I: Received Final Move Response (Success)
I: Releasing Association
PS>
```

And the C# that generates the refused error above:

```cs
var dicomClient = new DicomClient(host: [REMOVED], port: 104, useTls: false, callingAe: "TEST1", calledAe: "TEST2");

var cmove = new DicomCMoveRequest("TEST3", [StudyInstanceUID_REMOVED])
{
    OnResponseReceived = (request, response) =>
    {
        _logger.Debug($"{response.Status.Description} CMOVE");
    }
};

await dicomClient.AddRequestAsync(cmove);
await dicomClient.SendAsync();
```

```
> 2020-05-29 14:57:53.3171|DEBUG||Refused: SOP class not supported CMOVE
```

Any help you can provide would be appreciated as it does just appear to be a config/setup issue with how I am using fo-dicom.

**Comment by pcopley** [comment]
@gofal Is there any chance you could point me in the right direction here? I am following the example and while DCMTK works directly, the fo-dicom library gives me an error for the same command.

**Comment by gofal** [comment]
The message "SOP class not supported" is a result from the server and would tell, that the SOPClass (in case of CMoveRequest this is StudyRootQueryRetrieveInformationModelMOVE 1.2.840.10008.5.1.4.1.2.2.2) will not be accepted by the server. So this is typically an error you geht, if you use wrong configuration (wrong AETitle for example) of if the server is not configured well (your client/IP is not allowed to send the request).

Could you please use dcmtk tool with "-d" instead of "-v" as output option? And then also please add full logging to fo-dicom by adding `client.Options.LogDimseDatasets = true;` after the constructor. 

Then I will try to find the difference.

**Comment by gofal** [comment]
Do you have any new information about the issue?
