### ISSUE TITLE
DICOM file generated does not open

### ISSUE THREAD

**Issue by falandocomj** [fo-dicom/fo-dicom-samples#67]
Hello All,
DICOM file generated on SCP print does not open!
I tried in many ways. Thanks for the contribution!
fo-dicom 4.0.7

<code>

                    string receivingFolder = Path.Combine(Environment.CurrentDirectory, "PrintJobs");
                    string dir = Path.Combine(receivingFolder, DateTime.Now.ToString("yyyyddMM HHmmss"));
                    Directory.CreateDirectory(dir);

                    DicomFile file;
                    foreach (var box in filmSession.BasicFilmBoxes)
                    {

                        file = new DicomFile(box);
                        string filename = Path.Combine(dir, box.SOPInstanceUID.UID);
                        
                        file.Save(Path.Combine(filename));
                        
                        file.Save(Path.Combine(filename + "test2.dcm"));

                        var printerSettings = new PrinterSettings
                        {
                            PrinterName = "Microsoft XPS Document Writer",
                            PrintToFile = true,
                            PrintFileName = Path.Combine(dir, box.SOPInstanceUID.UID + "-test3.dcm")
                        };
                        printDocument = new PrintDocument
                        {
                            PrinterSettings = printerSettings,
                            DocumentName = box.SOPInstanceUID.UID,
                            PrintController = new StandardPrintController()
                        };
                        printDocument.Print();
                        printDocument.Dispose();
                    }
</code>

@anders9ustafsson

**Comment by gofal** [comment]
A Dicom Printjob has a hierachy. Highes level is a PrintSession (a job). this contains of several FilmBoxes (pages in the job). a FilmBox then has some ImageBoxes (images on the page) and those then again do have a ImageSequence (mostly one image but can be several images). So a printjob is organized completely different from a classical DICOM-file with the PixelData attribute etc. The file you are saving here is a valid DICOM-file, but no dicomviewer will show you the images as you would expect. Try running a StoreSCP instead of a PrintSCP to get the images.
