### ISSUE TITLE
.NET Core no codec registered

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom-samples#7]
Hi, 

I took some code from the example to test a send of a DicomCStoreRequest and I get No codec registered for tranfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression

Two questions:
1) To perform a C-STORE, why is a codec required?
2) Where is the codec library and how should I load it?  I currently have only 
<PackageReference Include="fo-dicom.NetCore" Version="3.0.2" /> specified.

Thank you!

**Comment by anders9ustafsson** [comment]
@buckstephenh Interestingly enough, there is a similar discussion ongoing in the Google Groups forum, [here](https://groups.google.com/forum/#!topic/fo-dicom/Qq2X5RUrXEw).

Since I don't know exactly what you have done, I have to make some assumptions, but here are a few important points:

1. There is currently no support for the JPEG Process 14 SV1 codec in .NET Core, right now it is only supported on .NET Framework and UWP, This is because .NET Core uses the managed C# library *LibJpeg.NET* for JPEG codecs, and this library does not support JPEG lossless and/or >8 bits.
2. When doing a C-STORE, the *fo-dicom* client will attempt to change the transfer syntax of a file if it is different from the negotiated accepted transfer syntax. I recommend that you dump the log from the network traffic to check what transfer syntax is being accepted in the negotiation.
3. Not sure which *fo-dicom* version you are using, but currently the codec support in the 3.0.2 ,NET Core release is limited to 8-bit lossy JPEG and 8-bit JPEG 2000. In upcoming releases there will be 16-bit JPEG 2000 support and full JPEG-LS support as well, but for JPEG there is currently no 12- (lossy) or 16-bit (lossless) support in sight for .NET Core. (Of course, if someone in the community would be willing to take on the task of implementing these missing pieces we would be extremely grateful.)

**Comment by anders9ustafsson** [comment]
@buckstephenh Did any of the above suggestions answer your question? I am closing this issue now, if you believe that the issue remains please re-open it.

**Comment by buckstephenh** [comment]
Yes thank you for the info.  I am proceeding with implementation and plan to add support for the missing pieces including codecs and another issue of the library eating exceptions when those issues with fo-dicom become the remaining blockers in my project.  Thanks for the project contribution and we at lifeIMAGE are looking forward to more exciting times together!

**Comment by buertlh** [comment]
@buckstephenh Hi buckstephenh, what's going on about implementation of supporting transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]):

**Comment by buckstephenh** [comment]
I haven’t circled back on this yet.  We need to assess the customer need outside of our own test data. 

Can I see through logging when a conversion is taking place?

Sent from my iPhone

On May 16, 2018, at 5:59 AM, buertlh <notifications@github.com> wrote:

@buckstephenh Hi buckstephenh, what's going on about implementation of supporting transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]):
